kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-dotnet-cicd-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: thin-csi
