apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-push-cli
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: >-
    This task is a rehash of the ClusterTask git-cli with the sole purpose of pushing
    to an already established git repo.
  params:
    - default: >-
        docker.io/alpine/git:v2.26.2@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f
      description: |
        The base image for the task.
      name: BASE_IMAGE
      type: string
    - default: ''
      description: |
        Git user name for performing git operation.
      name: GIT_USER_NAME
      type: string
    - default: ''
      description: |
        Git user email for performing git operation.
      name: GIT_USER_EMAIL
      type: string
    - default: /root
      description: >
        Absolute path to the user's home directory. Set this explicitly if you
        are running the image as a non-root user or have overridden

        the gitInitImage param with an image containing custom user
        configuration.
      name: USER_HOME
      type: string
    - default: 'true'
      description: Log the commands that are executed during `git-clone`'s operation.
      name: VERBOSE
      type: string
    - default: ''
      description: path of the updated gitops config directory
      name: CONFIG_CONTEXT_PATH
      type: string
    - default: ''
      description: Name of the updated gitops config
      name: CONFIG_APP_NAME
      type: string
  steps:
    - env:
        - name: PARAM_VERBOSE
          value: $(params.VERBOSE)
        - name: PARAM_USER_HOME
          value: $(params.USER_HOME)
      image: $(params.BASE_IMAGE)
      name: git-push
      resources: {}
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "${PARAM_VERBOSE}" = "true" ] ; then
          set -x
        fi

        if [ -d "${PARAM_USER_HOME}"/.ssh ] ; then
          echo ".ssh already exists"
        else 
          echo "Cannot find .ssh directory. Initiating copy to .ssh directory"
          cp -R $(workspaces.ssh-directory.path) "${PARAM_USER_HOME}"/.ssh
          chmod 700 "${PARAM_USER_HOME}"/.ssh
          chmod -R 400 "${PARAM_USER_HOME}"/.ssh/*
        fi

        # Setting up the config for the git.
        git config --global user.email "$(params.GIT_USER_EMAIL)"
        git config --global user.name "$(params.GIT_USER_NAME)"

        git add .

        git remote -v
        
        # if there are no unstaged changes to be committed
        if [ -n "$(git status --porcelain)" ]; then
          echo "committing and pushing changes to main..."
          git commit -m "Tekton: updating image tag of $(params.CONFIG_APP_NAME) to the latest git push"
          git push -u origin main
        else
          echo "no changes, skipping git push"
          exit 0
        fi
      workingDir: $(workspaces.source.path)/$(params.CONFIG_CONTEXT_PATH)
  workspaces:
    - description: A workspace that contains the fetched git repository and ssh credentials.
      name: source
    - description: ssh-directory for the credentials
      name: ssh-directory
      optional: true
