apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pipeline-test

configMapGenerator:
  - name: maven-settings
    options:
      disableNameSuffixHash: true
    files:
      - settings.xml

resources:
  - ../../base
  - configmap-argocd-env.yaml
  - secret-argocd-env.yaml
  - secret-git-ssh.yaml