kind: Secret
apiVersion: v1
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: git.test.com.au
data:
  known_hosts: >-
    ...
  ssh-privatekey: >-
    ...
type: kubernetes.io/ssh-auth
